CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

cash: cash.c
	$(CC) $(CFLAGS) cash.c -o cash $(LDLIBS)
CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

cash: cash.c
	$(CC) $(CFLAGS) cash.c -o cash $(LDLIBS)
