CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

readability: readability.c
	$(CC) $(CFLAGS) readability.c -o readability $(LDLIBS)
CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

readability: readability.c
	$(CC) $(CFLAGS) readability.c -o readability $(LDLIBS)
