CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

credit: credit.c
	$(CC) $(CFLAGS) credit.c -o credit $(LDLIBS)
CC = gcc
CFGLAGS = -g -Wall -Werror
LDLIBS = -lcs50 -lm

credit: credit.c
	$(CC) $(CFLAGS) credit.c -o credit $(LDLIBS)
